### PR TITLE
Improve development workflow

### PR DESCRIPTION
**Pull request by kemenaran**
Hi @willdurand! I've read your article, and spent some time fiddling with your Gitpod configuration for building Firefox. Thanks for the initial work on this, it really gave me the motivation to set up a full development environment on Gitpod!

While setting up a workspace, I made some cleanups and improvements to the development workflow.

## The issue I had, and improvements made

The main issue I had is that **Firefox was recompiled from scratch every time the workspace started** – which was really slow. I was working on C++ code, so I couldn't even use build artifacts.

With those changes:

- Firefox is built automatically only when creating the workspace (instead of being rebuilt every time),
- When re-opening the workspace, Firefox is just run from the version already built,
- The build cache is preserved between workspace runs.

## Implementation details

Technically, the change is mainly that the `command:` action of Gitpod is no longer "Building Firefox", but "Launching Firefox" (which makes sense).

And preserving the build cache means storing  the`.mozbuild` directory in a directory under `/workspace` instead (so that it get saved by Gitpod).

Tell me if that looks interesting to you!

### CODE REVIEW

**Comment by kemenaran** [comment]
@willdurand would it make sense for you to merge those commits – or is it better if I start maintaining my own gitpod reicipe for Firefox? :)

**Comment by willdurand** [comment]
Sorry, I need to get back to this PR..

I think it'd make sense to merge these changes as long as they make sense to me as well. If not, we can probably use branches to have different "flavors".

Anyway, I didn't need a Linux env lately so I haven't had a chance to try out these changes yet. Maybe it'll be fine.

Compiling on Gitpod is rather slow so one of my main criteria is how long it takes to get started.

**Comment by kemenaran** [comment]
Well, the initial startup time should be roughly the same (it still defaults to an artifacts build). What probably changes is the time when re-opening a container: all intermediate build products are now cached, which means the workspace takes longer to be saved and restored.

However, on re-opening, once the workspace is restored, there's no extra build time (not even an artifacts build): a restored binary of firefox is ready to be launched. And even re-building manually should only take less than a minute (because all builds products are cached).

In the end, for all builds (with artifacts or complete), the workspace creation time should be about the same, but the workspace re-opening should be much faster in all cases.

**Review by willdurand — APPROVED** [review]
I'd say, let's try it. Thanks!

**Pull request merged**
